# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      - pip install -U pip "setuptools>=59" wheel "unicorn==2.0.1.post1"
      - pip install git+https://github.com/angr/archinfo.git
      - pip install git+https://github.com/angr/pyvex.git
      - pip install git+https://github.com/angr/cle.git
      - pip install git+https://github.com/angr/claripy.git
      - pip install git+https://github.com/angr/ailment.git
      - pip install --no-build-isolation .[angrdb,docs,pcode]
