version: 1.0.{build}
image: Visual Studio 2015
init:
- ps: '#$blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1''))'
install:
- cmd: |
    "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
    cd \
    git clone https://github.com/angr/angr-dev.git
    cd angr-dev
    setup.bat %APPVEYOR_REPO_BRANCH%

test_script:
- cmd: |
    cd \angr-dev
    tests\appveyor_test.bat angr

build: off
