#!/usr/bin/env python3
"""Generate ``src/ailment/vexop_names.rs`` from pyvex's IROp enum.

The VEX ``IROp`` enum is contiguous starting at ``Iop_INVALID = 0x1400``, so we
emit the op-name strings in enum order and index them at runtime by
``op_int - IOP_BASE``. This is pure VEX-ISA data (not classification logic);
regenerate it whenever the bundled VEX is updated:

    python native/angr/scripts/gen_vexop_names.py
"""

from __future__ import annotations

import os

from pyvex.enums import irop_enums_to_ints

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "ailment", "vexop_names.rs")


def main() -> None:
    items = sorted(irop_enums_to_ints.items(), key=lambda kv: kv[1])
    lo = items[0][1]
    hi = items[-1][1]
    assert lo == 0x1400, f"unexpected IROp base {lo:#x}"
    ints = {v for _, v in items}
    assert all(i in ints for i in range(lo, hi + 1)), "IROp enum is not contiguous"

    lines = [
        "//! AUTO-GENERATED by `scripts/gen_vexop_names.py` -- do not edit by hand.",
        "//!",
        "//! Maps a VEX `IROp` integer to its enum name. The enum is contiguous",
        "//! from `IOP_BASE`, so `IROP_NAMES[op_int - IOP_BASE]` is the name.",
        "",
        "/// Value of `Iop_INVALID`; the base of the (contiguous) `IROp` enum.",
        f"pub const IOP_BASE: u32 = {lo:#x};",
        "",
        "/// Op names in `IROp` enum order, indexed by `op_int - IOP_BASE`.",
        "#[rustfmt::skip]",
        "pub static IROP_NAMES: &[&str] = &[",
    ]
    for name, _ in items:
        lines.append(f'    "{name}",')
    lines.append("];")
    lines.append("")

    with open(os.path.normpath(OUT), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {len(items)} op names to {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
