#include <libvex.h>
#include <stdio.h>
#include <string.h>
#include "pyvex_macros.h"

//////////////////////////
// IRExprTag translator //
//////////////////////////

const char *IRExprTag_to_str(IRExprTag t)
{
	switch (t)
	{
		PYVEX_ENUMCONV_TOSTRCASE(Iex_Binder)
		PYVEX_ENUMCONV_TOSTRCASE(Iex_Get)
		PYVEX_ENUMCONV_TOSTRCASE(Iex_GetI)
		PYVEX_ENUMCONV_TOSTRCASE(Iex_RdTmp)
		PYVEX_ENUMCONV_TOSTRCASE(Iex_Qop)
		PYVEX_ENUMCONV_TOSTRCASE(Iex_Triop)
		PYVEX_ENUMCONV_TOSTRCASE(Iex_Binop)
		PYVEX_ENUMCONV_TOSTRCASE(Iex_Unop)
		PYVEX_ENUMCONV_TOSTRCASE(Iex_Load)
		PYVEX_ENUMCONV_TOSTRCASE(Iex_Const)
		PYVEX_ENUMCONV_TOSTRCASE(Iex_Mux0X)
		PYVEX_ENUMCONV_TOSTRCASE(Iex_CCall)
		default:
			fprintf(stderr, "PyVEX: Unknown IRExprTag");
			return NULL;
	}
}

// TODO: speed this up
IRExprTag str_to_IRExprTag(const char *s)
{
	PYVEX_ENUMCONV_FROMSTR(Iex_Binder)
	PYVEX_ENUMCONV_FROMSTR(Iex_Get)
	PYVEX_ENUMCONV_FROMSTR(Iex_GetI)
	PYVEX_ENUMCONV_FROMSTR(Iex_RdTmp)
	PYVEX_ENUMCONV_FROMSTR(Iex_Qop)
	PYVEX_ENUMCONV_FROMSTR(Iex_Triop)
	PYVEX_ENUMCONV_FROMSTR(Iex_Binop)
	PYVEX_ENUMCONV_FROMSTR(Iex_Unop)
	PYVEX_ENUMCONV_FROMSTR(Iex_Load)
	PYVEX_ENUMCONV_FROMSTR(Iex_Const)
	PYVEX_ENUMCONV_FROMSTR(Iex_Mux0X)
	PYVEX_ENUMCONV_FROMSTR(Iex_CCall)

	return -1;
}

//////////////////////////
// IRStmtTag translator //
//////////////////////////

const char *IRStmtTag_to_str(IRStmtTag t)
{
	switch (t)
	{
		PYVEX_ENUMCONV_TOSTRCASE(Ist_NoOp)
		PYVEX_ENUMCONV_TOSTRCASE(Ist_IMark)
		PYVEX_ENUMCONV_TOSTRCASE(Ist_AbiHint)
		PYVEX_ENUMCONV_TOSTRCASE(Ist_Put)
		PYVEX_ENUMCONV_TOSTRCASE(Ist_PutI)
		PYVEX_ENUMCONV_TOSTRCASE(Ist_WrTmp)
		PYVEX_ENUMCONV_TOSTRCASE(Ist_Store)
		PYVEX_ENUMCONV_TOSTRCASE(Ist_CAS)
		PYVEX_ENUMCONV_TOSTRCASE(Ist_LLSC)
		PYVEX_ENUMCONV_TOSTRCASE(Ist_Dirty)
		PYVEX_ENUMCONV_TOSTRCASE(Ist_MBE)
		PYVEX_ENUMCONV_TOSTRCASE(Ist_Exit)
		default:
			fprintf(stderr, "PyVEX: Unknown IRStmtTag");
			return NULL;
	}
}

IRStmtTag str_to_IRStmtTag(const char *s)
{
	PYVEX_ENUMCONV_FROMSTR(Ist_NoOp)
	PYVEX_ENUMCONV_FROMSTR(Ist_IMark)
	PYVEX_ENUMCONV_FROMSTR(Ist_AbiHint)
	PYVEX_ENUMCONV_FROMSTR(Ist_Put)
	PYVEX_ENUMCONV_FROMSTR(Ist_PutI)
	PYVEX_ENUMCONV_FROMSTR(Ist_WrTmp)
	PYVEX_ENUMCONV_FROMSTR(Ist_Store)
	PYVEX_ENUMCONV_FROMSTR(Ist_CAS)
	PYVEX_ENUMCONV_FROMSTR(Ist_LLSC)
	PYVEX_ENUMCONV_FROMSTR(Ist_Dirty)
	PYVEX_ENUMCONV_FROMSTR(Ist_MBE)
	PYVEX_ENUMCONV_FROMSTR(Ist_Exit)

	return -1;
}

//////////////////////////
// IREndness translator //
//////////////////////////

const char *IREndness_to_str(IREndness t)
{
	switch (t)
	{
		PYVEX_ENUMCONV_TOSTRCASE(Iend_LE)
		PYVEX_ENUMCONV_TOSTRCASE(Iend_BE)
		default:
			fprintf(stderr, "PyVEX: Unknown IREndness");
			return NULL;
	}
}

IREndness str_to_IREndness(const char *s)
{
	PYVEX_ENUMCONV_FROMSTR(Iend_LE)
	PYVEX_ENUMCONV_FROMSTR(Iend_BE)

	return -1;
}

///////////////////////////
// IRJumpKind translator //
///////////////////////////

const char *IRJumpKind_to_str(IRJumpKind t)
{
	switch (t)
	{
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_INVALID)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_Boring)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_Call)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_Ret)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_ClientReq)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_Yield)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_EmWarn)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_EmFail)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_NoDecode)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_MapFail)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_TInval)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_NoRedir)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_SigTRAP)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_SigSEGV)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_SigBUS)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_Sys_syscall)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_Sys_int32)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_Sys_int128)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_Sys_int129)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_Sys_int130)
		PYVEX_ENUMCONV_TOSTRCASE(Ijk_Sys_sysenter)
		default:
			fprintf(stderr, "PyVEX: Unknown IRJumpKind");
			return NULL;
	}
}

IRJumpKind str_to_IRJumpKind(const char *s)
{
	PYVEX_ENUMCONV_FROMSTR(Ijk_INVALID)
	PYVEX_ENUMCONV_FROMSTR(Ijk_Boring)
	PYVEX_ENUMCONV_FROMSTR(Ijk_Call)
	PYVEX_ENUMCONV_FROMSTR(Ijk_Ret)
	PYVEX_ENUMCONV_FROMSTR(Ijk_ClientReq)
	PYVEX_ENUMCONV_FROMSTR(Ijk_Yield)
	PYVEX_ENUMCONV_FROMSTR(Ijk_EmWarn)
	PYVEX_ENUMCONV_FROMSTR(Ijk_EmFail)
	PYVEX_ENUMCONV_FROMSTR(Ijk_NoDecode)
	PYVEX_ENUMCONV_FROMSTR(Ijk_MapFail)
	PYVEX_ENUMCONV_FROMSTR(Ijk_TInval)
	PYVEX_ENUMCONV_FROMSTR(Ijk_NoRedir)
	PYVEX_ENUMCONV_FROMSTR(Ijk_SigTRAP)
	PYVEX_ENUMCONV_FROMSTR(Ijk_SigSEGV)
	PYVEX_ENUMCONV_FROMSTR(Ijk_SigBUS)
	PYVEX_ENUMCONV_FROMSTR(Ijk_Sys_syscall)
	PYVEX_ENUMCONV_FROMSTR(Ijk_Sys_int32)
	PYVEX_ENUMCONV_FROMSTR(Ijk_Sys_int128)
	PYVEX_ENUMCONV_FROMSTR(Ijk_Sys_int129)
	PYVEX_ENUMCONV_FROMSTR(Ijk_Sys_int130)
	PYVEX_ENUMCONV_FROMSTR(Ijk_Sys_sysenter)

	return -1;
}

///////////////////////////
// IRConstTag translator //
///////////////////////////

const char *IRConstTag_to_str(IRConstTag t)
{
	switch (t)
	{
		PYVEX_ENUMCONV_TOSTRCASE(Ico_U1)
		PYVEX_ENUMCONV_TOSTRCASE(Ico_U8)
		PYVEX_ENUMCONV_TOSTRCASE(Ico_U16)
		PYVEX_ENUMCONV_TOSTRCASE(Ico_U32)
		PYVEX_ENUMCONV_TOSTRCASE(Ico_U64)
		PYVEX_ENUMCONV_TOSTRCASE(Ico_F32)
		PYVEX_ENUMCONV_TOSTRCASE(Ico_F32i)
		PYVEX_ENUMCONV_TOSTRCASE(Ico_F64)
		PYVEX_ENUMCONV_TOSTRCASE(Ico_F64i)
		PYVEX_ENUMCONV_TOSTRCASE(Ico_V128)
		PYVEX_ENUMCONV_TOSTRCASE(Ico_V256)
		default:
			fprintf(stderr, "PyVEX: Unknown IRConstTag");
			return NULL;
	}
}

IRConstTag str_to_IRConstTag(const char *s)
{
	PYVEX_ENUMCONV_FROMSTR(Ico_U1)
	PYVEX_ENUMCONV_FROMSTR(Ico_U8)
	PYVEX_ENUMCONV_FROMSTR(Ico_U16)
	PYVEX_ENUMCONV_FROMSTR(Ico_U32)
	PYVEX_ENUMCONV_FROMSTR(Ico_U64)
	PYVEX_ENUMCONV_FROMSTR(Ico_F32)
	PYVEX_ENUMCONV_FROMSTR(Ico_F32i)
	PYVEX_ENUMCONV_FROMSTR(Ico_F64)
	PYVEX_ENUMCONV_FROMSTR(Ico_F64i)
	PYVEX_ENUMCONV_FROMSTR(Ico_V128)
	PYVEX_ENUMCONV_FROMSTR(Ico_V256)

	return -1;
}

////////////
// IRType //
////////////

const char *IRType_to_str(IRType t)
{
	switch (t)
	{
		PYVEX_ENUMCONV_TOSTRCASE(Ity_INVALID)
		PYVEX_ENUMCONV_TOSTRCASE(Ity_I1)
		PYVEX_ENUMCONV_TOSTRCASE(Ity_I8)
		PYVEX_ENUMCONV_TOSTRCASE(Ity_I16)
		PYVEX_ENUMCONV_TOSTRCASE(Ity_I32)
		PYVEX_ENUMCONV_TOSTRCASE(Ity_I64)
		PYVEX_ENUMCONV_TOSTRCASE(Ity_I128)
		PYVEX_ENUMCONV_TOSTRCASE(Ity_F32)
		PYVEX_ENUMCONV_TOSTRCASE(Ity_F64)
		PYVEX_ENUMCONV_TOSTRCASE(Ity_D32)
		PYVEX_ENUMCONV_TOSTRCASE(Ity_D64)
		PYVEX_ENUMCONV_TOSTRCASE(Ity_D128)
		PYVEX_ENUMCONV_TOSTRCASE(Ity_F128)
		PYVEX_ENUMCONV_TOSTRCASE(Ity_V128)
		PYVEX_ENUMCONV_TOSTRCASE(Ity_V256)

		default:
			fprintf(stderr, "PyVEX: Unknown IRType");
			return NULL;
	}
}

IRType str_to_IRType(const char *s)
{
	PYVEX_ENUMCONV_FROMSTR(Ity_INVALID)
	PYVEX_ENUMCONV_FROMSTR(Ity_I1)
	PYVEX_ENUMCONV_FROMSTR(Ity_I8)
	PYVEX_ENUMCONV_FROMSTR(Ity_I16)
	PYVEX_ENUMCONV_FROMSTR(Ity_I32)
	PYVEX_ENUMCONV_FROMSTR(Ity_I64)
	PYVEX_ENUMCONV_FROMSTR(Ity_I128)
	PYVEX_ENUMCONV_FROMSTR(Ity_F32)
	PYVEX_ENUMCONV_FROMSTR(Ity_F64)
	PYVEX_ENUMCONV_FROMSTR(Ity_D32)
	PYVEX_ENUMCONV_FROMSTR(Ity_D64)
	PYVEX_ENUMCONV_FROMSTR(Ity_D128)
	PYVEX_ENUMCONV_FROMSTR(Ity_F128)
	PYVEX_ENUMCONV_FROMSTR(Ity_V128)
	PYVEX_ENUMCONV_FROMSTR(Ity_V256)

	return -1;
}
