"""Type stubs for ``angr.rustylib.claripy.ast.base``."""

from collections.abc import Sequence
from typing import Any, Self

from angr.rustylib.claripy.annotation import Annotation

class Base:
    @property
    def name(self) -> str | None: ...
    @property
    def _encoded_name(self) -> bytes | None: ...
    @property
    def _errored(self) -> set[Any]: ...
    @property
    def op(self) -> str: ...
    @property
    def args(self) -> list[Any]: ...
    @property
    def variables(self) -> frozenset[str]: ...
    @property
    def symbolic(self) -> bool: ...
    @property
    def concrete(self) -> bool: ...
    @property
    def annotations(self) -> list[Annotation]: ...
    @property
    def depth(self) -> int: ...
    def hash(self) -> int: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def shallow_repr(self, max_depth: int = 2) -> str: ...
    def canonicalize(
        self, var_map: dict[int, Base] | None = None, counter: Any | None = None
    ) -> tuple[dict[int, Base], Any, Self]: ...
    def identical(self, other: Base) -> bool: ...
    def is_leaf(self) -> bool: ...
    def simplify(self, respect_annotations: bool = True) -> Self: ...
    def replace(self, from_: Base, to: Base, /) -> Self: ...
    def has_annotation_type(self, annotation_type: type[Annotation]) -> bool: ...
    def get_annotations_by_type(self, annotation_type: type[Annotation]) -> list[Annotation]: ...
    def get_annotation(self, annotation_type: type[Annotation]) -> Annotation | None: ...
    def append_annotation(self, annotation: Annotation) -> Self: ...
    def append_annotations(self, annotations: Sequence[Annotation]) -> Self: ...
    def annotate(self, *annotations: Annotation, remove_annotations: Sequence[Annotation] | None = None) -> Self: ...
    def insert_annotations(self, annotations: Sequence[Annotation]) -> Self: ...
    def replace_annotations(self, annotations: Sequence[Annotation]) -> Self: ...
    def remove_annotation(self, annotation: Annotation) -> Self: ...
    def remove_annotations(self, annotations: Sequence[Annotation]) -> Self: ...
    def clear_annotations(self) -> Self: ...
    def clear_annotation_type(self, annotation_type: type[Annotation]) -> Self: ...

__all__ = ["Base"]
