"""Type stubs for ``angr.rustylib.claripy.ast.bv``."""

from collections.abc import Sequence
from typing import Any, overload

from angr.rustylib.claripy.annotation import Annotation
from angr.rustylib.claripy.ast.bits import Bits
from angr.rustylib.claripy.ast.bool import Bool
from angr.rustylib.claripy.ast.fp import FP, RM, FSort

type _BVLike = BV | int | Bool | bytes | str

class BV(Bits):
    def __init__(self, op: str, args: Sequence[Any], annotations: Sequence[Annotation] | None = None) -> None: ...
    def is_true(self) -> bool: ...
    def is_false(self) -> bool: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def concrete_value(self) -> int | None: ...
    @property
    def reversed(self) -> BV: ...
    @property
    def cardinality(self) -> int: ...
    @property
    def singlevalued(self) -> bool: ...
    @property
    def multivalued(self) -> bool: ...
    def __getitem__(self, key: int | slice, /) -> BV: ...
    def raw_to_bv(self) -> BV: ...
    def raw_to_fp(self) -> FP: ...
    def to_bv(self) -> BV: ...
    def val_to_fp(self, sort: FSort | None = None, signed: bool = True, rm: RM | None = None) -> FP: ...
    def __add__(self, value: _BVLike, /) -> BV: ...
    def __radd__(self, value: _BVLike, /) -> BV: ...
    def __sub__(self, value: _BVLike, /) -> BV: ...
    def __rsub__(self, value: _BVLike, /) -> BV: ...
    def __mul__(self, value: _BVLike, /) -> BV: ...
    def __rmul__(self, value: _BVLike, /) -> BV: ...
    def __truediv__(self, value: _BVLike, /) -> BV: ...
    def __rtruediv__(self, value: _BVLike, /) -> BV: ...
    def __floordiv__(self, value: _BVLike, /) -> BV: ...
    def __rfloordiv__(self, value: _BVLike, /) -> BV: ...
    def __mod__(self, value: _BVLike, /) -> BV: ...
    def __rmod__(self, value: _BVLike, /) -> BV: ...
    def SDiv(self, other: _BVLike) -> BV: ...
    def SMod(self, other: _BVLike) -> BV: ...
    def __and__(self, value: _BVLike, /) -> BV: ...
    def __rand__(self, value: _BVLike, /) -> BV: ...
    def __or__(self, value: _BVLike, /) -> BV: ...
    def __ror__(self, value: _BVLike, /) -> BV: ...
    def __xor__(self, value: _BVLike, /) -> BV: ...
    def __rxor__(self, value: _BVLike, /) -> BV: ...
    def __lshift__(self, value: _BVLike, /) -> BV: ...
    def __rlshift__(self, value: _BVLike, /) -> BV: ...
    def __rshift__(self, value: _BVLike, /) -> BV: ...
    def __rrshift__(self, value: _BVLike, /) -> BV: ...
    def LShR(self, other: _BVLike) -> BV: ...
    def __neg__(self) -> BV: ...
    def __invert__(self) -> BV: ...
    def __pos__(self) -> BV: ...
    def __eq__(self, value: _BVLike, /) -> Bool: ...  # type: ignore[override]
    def __ne__(self, value: _BVLike, /) -> Bool: ...  # type: ignore[override]
    def __hash__(self) -> int: ...
    def __lt__(self, value: _BVLike, /) -> Bool: ...
    def __le__(self, value: _BVLike, /) -> Bool: ...
    def __gt__(self, value: _BVLike, /) -> Bool: ...
    def __ge__(self, value: _BVLike, /) -> Bool: ...
    def ULT(self, other: _BVLike) -> Bool: ...
    def ULE(self, other: _BVLike) -> Bool: ...
    def UGT(self, other: _BVLike) -> Bool: ...
    def UGE(self, other: _BVLike) -> Bool: ...
    def SLT(self, other: _BVLike) -> Bool: ...
    def SLE(self, other: _BVLike) -> Bool: ...
    def SGT(self, other: _BVLike) -> Bool: ...
    def SGE(self, other: _BVLike) -> Bool: ...
    def Extract(self, upper_bound: int, lower_bound: int) -> BV: ...
    def concat(self, *args: _BVLike) -> BV: ...
    def zero_extend(self, amount: int) -> BV: ...
    def sign_extend(self, amount: int) -> BV: ...
    def get_bytes(self, index: int, size: int) -> BV: ...
    def get_byte(self, index: int) -> BV: ...
    def chop(self, bits: int) -> list[BV]: ...
    def union(self, other: _BVLike) -> BV: ...
    def intersection(self, other: _BVLike) -> BV: ...
    def widen(self, other: _BVLike) -> BV: ...
    def __reduce__(self) -> tuple[type[BV], tuple[str, list[Any], list[Annotation]]]: ...

def BVS(name: str | bytes, size: int, explicit_name: bool = False) -> BV: ...
def BVV(value: int | bytes | str, size: int | None = None) -> BV: ...
@overload
def Not(b: Bool) -> Bool: ...
@overload
def Not(b: BV) -> BV: ...
@overload
def And(*args: Bool | bool) -> Bool: ...
@overload
def And(lhs: _BVLike, rhs: _BVLike, /) -> BV: ...
@overload
def Or(*args: Bool | bool) -> Bool: ...
@overload
def Or(lhs: _BVLike, rhs: _BVLike, /) -> BV: ...
@overload
def xor(a: Bool, b: Bool | bool) -> Bool: ...
@overload
def xor(a: BV | int | bytes | str, b: _BVLike) -> BV: ...
def Add(lhs: _BVLike, rhs: _BVLike) -> BV: ...
def Sub(lhs: _BVLike, rhs: _BVLike) -> BV: ...
def Mul(lhs: _BVLike, rhs: _BVLike) -> BV: ...
def UDiv(lhs: _BVLike, rhs: _BVLike) -> BV: ...
def SDiv(lhs: _BVLike, rhs: _BVLike) -> BV: ...
def UMod(lhs: _BVLike, rhs: _BVLike) -> BV: ...
def SMod(lhs: _BVLike, rhs: _BVLike) -> BV: ...
def ShL(lhs: _BVLike, rhs: _BVLike) -> BV: ...
def LShR(lhs: _BVLike, rhs: _BVLike) -> BV: ...
def AShR(lhs: _BVLike, rhs: _BVLike) -> BV: ...
def RotateLeft(lhs: _BVLike, rhs: _BVLike) -> BV: ...
def RotateRight(lhs: _BVLike, rhs: _BVLike) -> BV: ...
def Concat(*args: _BVLike) -> BV: ...
def Extract(upper: int, lower: int, base: BV) -> BV: ...
def ZeroExt(amount: int, base: BV) -> BV: ...
def SignExt(amount: int, base: BV) -> BV: ...
def Reverse(base: BV) -> BV: ...
def ULT(lhs: _BVLike, rhs: _BVLike) -> Bool: ...
def ULE(lhs: _BVLike, rhs: _BVLike) -> Bool: ...
def UGT(lhs: _BVLike, rhs: _BVLike) -> Bool: ...
def UGE(lhs: _BVLike, rhs: _BVLike) -> Bool: ...
def SLT(lhs: _BVLike, rhs: _BVLike) -> Bool: ...
def SLE(lhs: _BVLike, rhs: _BVLike) -> Bool: ...
def SGT(lhs: _BVLike, rhs: _BVLike) -> Bool: ...
def SGE(lhs: _BVLike, rhs: _BVLike) -> Bool: ...
def Eq_(lhs: _BVLike, rhs: _BVLike) -> Bool: ...
@overload
def If(cond: Bool | bool | int | BV, then_: BV, else_: _BVLike) -> BV: ...
@overload
def If(cond: Bool | bool | int | BV, then_: _BVLike, else_: BV) -> BV: ...
def SI(bits: int, stride: int, lower_bound: int, upper_bound: int) -> BV: ...
def ESI(bits: int) -> BV: ...
def VS(bits: int, region_id: str, region_base_addr: int, value: _BVLike) -> BV: ...
def union(lhs: _BVLike, rhs: _BVLike) -> BV: ...
def intersection(lhs: _BVLike, rhs: _BVLike) -> BV: ...
def widen(lhs: _BVLike, rhs: _BVLike) -> BV: ...

__all__ = [
    "BV",
    "BVS",
    "BVV",
    "ESI",
    "SGE",
    "SGT",
    "SI",
    "SLE",
    "SLT",
    "UGE",
    "UGT",
    "ULE",
    "ULT",
    "VS",
    "AShR",
    "Add",
    "And",
    "Concat",
    "Eq_",
    "Extract",
    "If",
    "LShR",
    "Mul",
    "Not",
    "Or",
    "Reverse",
    "RotateLeft",
    "RotateRight",
    "SDiv",
    "SMod",
    "ShL",
    "SignExt",
    "Sub",
    "UDiv",
    "UMod",
    "ZeroExt",
    "intersection",
    "union",
    "widen",
    "xor",
]
