"""Type stubs for ``angr.rustylib.claripy.ast.strings``."""

from collections.abc import Sequence
from typing import Any

from angr.rustylib.claripy.annotation import Annotation
from angr.rustylib.claripy.ast.base import Base
from angr.rustylib.claripy.ast.bool import Bool
from angr.rustylib.claripy.ast.bv import BV

type _BVLike = BV | int | Bool | bytes | str

class String(Base):
    def __init__(self, op: str, args: Sequence[Any], annotations: Sequence[Annotation] | None = None) -> None: ...
    @property
    def concrete_value(self) -> str | None: ...
    def __add__(self, value: String, /) -> String: ...
    def __eq__(self, value: String, /) -> Bool: ...  # type: ignore[override]
    def __ne__(self, value: String, /) -> Bool: ...  # type: ignore[override]
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[type[String], tuple[str, list[Any], list[Annotation]]]: ...

def StringS(name: str | bytes, explicit_name: bool = False) -> String: ...
def StringV(value: str) -> String: ...
def StrLen(s: String) -> BV: ...
def StrConcat(s1: String, s2: String) -> String: ...
def StrSubstr(start: _BVLike, size: _BVLike, base: String) -> String: ...
def StrContains(haystack: String, needle: String) -> Bool: ...
def StrIndexOf(haystack: String, needle: String, start: _BVLike) -> BV: ...
def StrReplace(haystack: String, needle: String, replacement: String) -> String: ...
def StrPrefixOf(needle: String, haystack: String) -> Bool: ...
def StrSuffixOf(needle: String, haystack: String) -> Bool: ...
def StrToInt(s: String) -> BV: ...
def IntToStr(bv: BV) -> String: ...
def StrIsDigit(s: String) -> Bool: ...
def StrEq(s1: String, s2: String) -> Bool: ...
def StrNeq(s1: String, s2: String) -> Bool: ...

__all__ = [
    "IntToStr",
    "StrConcat",
    "StrContains",
    "StrEq",
    "StrIndexOf",
    "StrIsDigit",
    "StrLen",
    "StrNeq",
    "StrPrefixOf",
    "StrReplace",
    "StrSubstr",
    "StrSuffixOf",
    "StrToInt",
    "String",
    "StringS",
    "StringV",
]
