"""Type stubs for ``angr.rustylib.ailment`` -- the Rust port of the AIL
data classes.

Phase D collapsed the per-class hierarchy into a single ``Expression``
pyclass (wrapping the inline ``AilExpression`` / ``ExprInner`` fat
enum) and a single ``Statement`` pyclass (wrapping ``AilStatement`` /
``StmtInner``). Per-variant marker classes (``Const``, ``BinaryOp``,
``Assignment``, ...) live on the Python side in
``angr.ailment.expression`` and ``angr.ailment.statement`` and dispatch
via metaclass ``__instancecheck__`` on the variant tag.

The rustlib surface is intentionally minimal:

* ``Expression`` / ``Statement`` -- the universal pyclasses
* ``Block`` -- the AIL Block container
* ``VirtualVariableCategory`` / ``ConvertType`` -- the AIL enums
* ``TagsView`` / ``TagsKeyIter`` -- the tag plumbing
* ``dumps`` / ``loads`` -- module-level byte serialization helpers

Variant-specific properties (``Const.value``, ``BinaryOp.op``, ...)
are accessible on the ``Expression`` / ``Statement`` instance through
the same getter names the legacy per-class pyclasses exposed -- the
attribute is dispatched on the variant tag and raises
``AttributeError`` when called on the wrong variant.
"""

from collections.abc import Iterator
from typing import Any, ClassVar, Self

# ---------------------------------------------------------------------------
# Tags
# ---------------------------------------------------------------------------

class TagsView:
    def __init__(self) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def keys(self) -> TagsKeyIter: ...
    def values(self) -> list[Any]: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def pop(self, key: str, default: Any = ...) -> Any: ...
    def update(self, other: Any) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> dict[str, Any]: ...
    def __eq__(self, other: object) -> bool: ...

class TagsKeyIter:
    def __iter__(self) -> Iterator[str]: ...
    def __next__(self) -> str: ...

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class VirtualVariableCategory:
    REGISTER: ClassVar[VirtualVariableCategory]
    STACK: ClassVar[VirtualVariableCategory]
    PARAMETER: ClassVar[VirtualVariableCategory]
    TMP: ClassVar[VirtualVariableCategory]
    COMBO_REGISTER: ClassVar[VirtualVariableCategory]
    UNKNOWN: ClassVar[VirtualVariableCategory]
    @staticmethod
    def from_int(value: int) -> VirtualVariableCategory | None: ...
    @property
    def value(self) -> int: ...

class ConvertType:
    TYPE_INT: ClassVar[ConvertType]
    TYPE_FP: ClassVar[ConvertType]
    @property
    def value(self) -> int: ...

# ---------------------------------------------------------------------------
# Expression -- single fat-enum pyclass
# ---------------------------------------------------------------------------

class Expression:
    """Universal Phase D AIL Expression pyclass.

    Backs every legacy per-class Expression subtype (Const, BinaryOp,
    Load, ...) via the inline ``ExprInner`` fat enum. The variant tag is
    exposed as the ``kind`` property; per-variant accessors below raise
    ``AttributeError`` when called on the wrong variant.
    """

    # --- Header accessors (every variant) ------------------------------
    idx: int
    bits: int
    @property
    def depth(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def tags(self) -> TagsView: ...
    @property
    def kind(self) -> str: ...
    def clear_hash(self) -> None: ...
    variable_offset: int

    # --- Common variant-specific accessors -----------------------------
    # Each raises ``AttributeError`` on a variant that doesn't carry
    # the slot.
    @property
    def value(self) -> Any: ...
    @property
    def value_int(self) -> int: ...
    @property
    def value_float(self) -> float: ...
    @property
    def is_int(self) -> bool: ...
    @property
    def sign_bit(self) -> int: ...
    @property
    def variable(self) -> Any | None: ...
    @property
    def tmp_idx(self) -> int | None: ...
    @property
    def reg_offset(self) -> int: ...
    @property
    def registers(self) -> list[Expression]: ...
    @property
    def src_and_vvars(self) -> list[Any]: ...
    @property
    def varid(self) -> int: ...
    @property
    def category(self) -> VirtualVariableCategory: ...
    @property
    def oident(self) -> Any: ...
    @property
    def reg_vvars(self) -> dict[int, Expression]: ...
    @property
    def was_reg(self) -> bool: ...
    @property
    def was_stack(self) -> bool: ...
    @property
    def was_parameter(self) -> bool: ...
    @property
    def was_tmp(self) -> bool: ...
    @property
    def was_combo_reg(self) -> bool: ...
    @property
    def parameter_category(self) -> VirtualVariableCategory | None: ...
    @property
    def parameter_reg_offset(self) -> int | None: ...
    @property
    def parameter_stack_offset(self) -> int | None: ...
    @property
    def stack_offset(self) -> int: ...
    @property
    def reg_offsets(self) -> tuple[int, ...]: ...
    @property
    def op(self) -> str: ...
    @property
    def verbose_op(self) -> str: ...
    @property
    def operand(self) -> Expression: ...
    @property
    def operands(self) -> tuple[Expression, ...] | list[Expression]: ...
    @property
    def from_bits(self) -> int: ...
    @property
    def to_bits(self) -> int: ...
    @property
    def is_signed(self) -> bool: ...
    @property
    def from_type(self) -> Any: ...
    @property
    def to_type(self) -> Any: ...
    @property
    def rounding_mode(self) -> Any | None: ...
    @property
    def signed(self) -> bool: ...
    @property
    def floating_point(self) -> bool: ...
    @property
    def addr(self) -> Expression: ...
    @property
    def endness(self) -> str: ...
    @property
    def guard(self) -> Expression | None: ...
    @property
    def alt(self) -> Expression | None: ...
    @property
    def cond(self) -> Expression: ...
    @property
    def iftrue(self) -> Expression: ...
    @property
    def iffalse(self) -> Expression: ...
    @property
    def base(self) -> Any: ...
    @property
    def offset(self) -> Any: ...
    @property
    def data(self) -> Any: ...
    @property
    def target(self) -> Any: ...
    @property
    def calling_convention(self) -> Any | None: ...
    @property
    def prototype(self) -> Any | None: ...
    @property
    def args(self) -> Any: ...
    @property
    def arg_vvars(self) -> tuple[Expression, ...] | None: ...
    @property
    def callee(self) -> str: ...
    @property
    def mfx(self) -> str | None: ...
    @property
    def maddr(self) -> Expression | None: ...
    @property
    def msize(self) -> int | None: ...
    @property
    def stmts(self) -> list[Any]: ...
    @property
    def expr(self) -> Expression: ...
    @property
    def name(self) -> str: ...
    @property
    def fields(self) -> Any: ...
    @property
    def field_offsets(self) -> dict[str, int]: ...
    @property
    def field_names(self) -> dict[int, str]: ...
    @property
    def elements(self) -> Any: ...
    @property
    def length(self) -> int: ...
    @property
    def variant(self) -> Any: ...
    @property
    def defs(self) -> list[Any]: ...
    @property
    def src(self) -> Expression: ...
    @property
    def delimiter(self) -> str: ...
    @property
    def returnty(self) -> Any | None: ...
    def get_field(self, name: str) -> Any | None: ...

    # --- Equality / hash / methods -------------------------------------
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def _hash_core(self) -> int: ...
    def likes(self, other: Any) -> bool: ...
    def matches(self, other: Any) -> bool: ...
    def replace(self, old_expr: Any, new_expr: Any) -> tuple[bool, Expression]: ...
    def has_atom(self, atom: Any, identity: bool = True) -> bool: ...
    def copy(self) -> Self: ...
    def deep_copy(self, manager: Any) -> Self: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: Any) -> Self: ...
    def __reduce__(self) -> tuple[Any, ...]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

    # --- Serialization -------------------------------------------------
    def to_bytes(self) -> bytes: ...
    @classmethod
    def from_bytes(cls, data: bytes) -> Expression: ...

# ---------------------------------------------------------------------------
# Statement -- single fat-enum pyclass
# ---------------------------------------------------------------------------

class Statement:
    """Universal Phase D AIL Statement pyclass.

    Backs every legacy per-class Statement subtype (Assignment, Store,
    Jump, ...) via the inline ``StmtInner`` fat enum. Per-variant
    accessors raise ``AttributeError`` on the wrong variant.
    """

    # --- Header accessors ---------------------------------------------
    idx: int
    @property
    def tags(self) -> TagsView: ...
    @property
    def kind(self) -> str: ...
    @property
    def depth(self) -> int: ...
    def clear_hash(self) -> None: ...

    # --- Variant-specific accessors -----------------------------------
    @property
    def dst(self) -> Expression: ...
    @property
    def src(self) -> Expression: ...
    @property
    def name(self) -> str: ...
    @property
    def addr(self) -> Expression: ...
    @property
    def data(self) -> Expression: ...
    @property
    def size(self) -> int: ...
    @property
    def endness(self) -> str: ...
    @property
    def guard(self) -> Expression | None: ...
    @property
    def variable(self) -> Any | None: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def target(self) -> Any: ...
    @property
    def target_idx(self) -> int | None: ...
    @property
    def condition(self) -> Expression: ...
    @property
    def true_target(self) -> Any | None: ...
    @property
    def false_target(self) -> Any | None: ...
    @property
    def true_target_idx(self) -> int | None: ...
    @property
    def false_target_idx(self) -> int | None: ...
    @property
    def expr(self) -> Expression: ...
    @property
    def ret_expr(self) -> Expression | None: ...
    @property
    def fp_ret_expr(self) -> Expression | None: ...
    @property
    def ret_exprs(self) -> list[Expression]: ...
    @property
    def data_lo(self) -> Expression: ...
    @property
    def data_hi(self) -> Expression | None: ...
    @property
    def expd_lo(self) -> Expression: ...
    @property
    def expd_hi(self) -> Expression | None: ...
    @property
    def old_lo(self) -> Expression: ...
    @property
    def old_hi(self) -> Expression | None: ...
    @property
    def dirty(self) -> Expression: ...

    # --- Equality / hash / methods -------------------------------------
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def _hash_core(self) -> int: ...
    def likes(self, other: Any) -> bool: ...
    def matches(self, other: Any) -> bool: ...
    def replace(self, old_expr: Any, new_expr: Any) -> tuple[bool, Statement]: ...
    def has_atom(self, atom: Any, identity: bool = True) -> bool: ...
    def copy(self) -> Self: ...
    def deep_copy(self, manager: Any) -> Self: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: Any) -> Self: ...
    def __reduce__(self) -> tuple[Any, ...]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

    # --- Serialization -------------------------------------------------
    def to_bytes(self) -> bytes: ...
    @classmethod
    def from_bytes(cls, data: bytes) -> Statement: ...

# ---------------------------------------------------------------------------
# Block
# ---------------------------------------------------------------------------

class Block:
    addr: int
    original_size: int | None
    idx: int | None
    statements: list[Statement]
    def __init__(
        self,
        addr: int,
        original_size: int | None = ...,
        *,
        statements: list[Statement] | None = ...,
        idx: int | None = ...,
    ) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: Any) -> Self: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def copy(self) -> Self: ...
    def to_bytes(self) -> bytes: ...
    @classmethod
    def from_bytes(cls, data: bytes) -> Block: ...

# ---------------------------------------------------------------------------
# Module-level helpers
# ---------------------------------------------------------------------------

def dumps(obj: Any) -> bytes: ...
def loads(data: bytes) -> Any: ...
