PRESENT_JUMPKIND: int
PRESENT_INS_ADDR: int
PRESENT_STMT_IDX: int

class CfgGraph:
    """
    Packed storage for the whole-program CFG graph behind CFGModel.graph: a node table keyed by (addr, size),
    an address index, and an edge table with typed edge attributes (jumpkind, ins_addr, stmt_idx).

    Node ids are indices into the node table and are stable for the lifetime of the graph; remove_node detaches
    a node, and re-adding the same key allocates a fresh id (so node iteration order matches networkx).
    """

    def __init__(self) -> None: ...
    def copy(self) -> CfgGraph: ...
    def clear(self) -> None: ...
    def number_of_nodes(self) -> int: ...
    def number_of_edges(self) -> int: ...
    def add_node(self, addr: int, size: int) -> tuple[int, bool]:
        """networkx add_node. Returns (id, created)."""

    def find_node(self, addr: int, size: int) -> int | None: ...
    def contains_node(self, idx: int) -> bool: ...
    def node_key(self, idx: int) -> tuple[int, int]: ...
    def node_addr(self, idx: int) -> int: ...
    def nodes(self) -> list[int]:
        """Live node ids in insertion order."""

    def node_keys(self) -> list[tuple[int, int]]: ...
    def remove_node(self, idx: int) -> bool: ...
    def nodes_at_addr(self, addr: int) -> list[int]: ...
    def first_node_at_addr(self, addr: int) -> int | None: ...
    def has_addr(self, addr: int) -> bool: ...
    def addrs(self) -> list[int]: ...
    def add_edge(
        self,
        src: int,
        dst: int,
        present: int = 0,
        jumpkind: str | None = None,
        ins_addr: int | None = None,
        stmt_idx: int | None = None,
    ) -> bool:
        """networkx add_edge; attributes whose PRESENT_* bit is set overwrite, the others are kept. Returns True
        if the edge is new."""

    def remove_edge(self, src: int, dst: int) -> bool: ...
    def has_edge(self, src: int, dst: int) -> bool: ...
    def edge_data(self, src: int, dst: int) -> dict | None: ...
    def edge_jumpkind(self, src: int, dst: int) -> str | None: ...
    def edges(self) -> list[tuple[int, int]]: ...
    def edges_with_data(self) -> list[tuple[int, int, dict]]: ...
    def out_edges(self, idx: int) -> list[tuple[int, int]]: ...
    def in_edges(self, idx: int) -> list[tuple[int, int]]: ...
    def out_edges_with_data(self, idx: int) -> list[tuple[int, int, dict]]: ...
    def in_edges_with_data(self, idx: int) -> list[tuple[int, int, dict]]: ...
    def successors(self, idx: int) -> list[int]: ...
    def predecessors(self, idx: int) -> list[int]: ...
    def out_degree(self, idx: int) -> int: ...
    def in_degree(self, idx: int) -> int: ...
    def is_call_destination(self, idx: int) -> bool: ...
    def call_destinations(self) -> list[int]: ...
    def to_bytes(self) -> bytes: ...
    @classmethod
    def from_bytes(cls, data: bytes) -> CfgGraph: ...
