from collections.abc import Callable
from typing import Any, Protocol

PRESENT_JUMPKIND: int
PRESENT_INS_ADDR: int
PRESENT_STMT_IDX: int
DEFAULT_WINDOW_SHIFT: int

class SegmentBackend(Protocol):
    """Where evicted segment blobs go; windows are ``addr >> window_shift``."""

    def get(self, window: int) -> bytes | None: ...
    def put(self, window: int, data: bytes) -> None: ...
    def delete(self, window: int) -> None: ...
    def delete_all(self) -> None: ...

class CfgGraph:
    """
    Packed, segmented storage for the whole-program CFG graph behind CFGModel.graph: nodes keyed by (addr, size),
    an address index, and edges with typed attributes (jumpkind, ins_addr, stmt_idx).

    The graph is partitioned into address windows of 2**window_shift bytes; a node id packs (segment, local index)
    and is stable while the node lives (a removed node's local index may be reused). Node iteration order is
    insertion order and successors/predecessors are in insertion order, as with networkx.

    With a backend attached, resident segments are kept under a byte budget (LRU); dirty segments are written back
    on eviction and reloaded on demand.
    """

    def __init__(self, window_shift: int = ...) -> None: ...
    def copy(self) -> CfgGraph:
        """A fully resident copy without a backend."""

    def clear(self) -> None: ...
    @property
    def window_shift(self) -> int: ...

    # paging
    def attach_backend(self, backend: SegmentBackend, budget_bytes: int) -> None: ...
    def attach_memory_backend(self, budget_bytes: int) -> None: ...
    def detach_backend(self) -> None:
        """Load everything back and drop the backend (its blobs are deleted)."""

    def set_paging_policy(self, threshold: int, callback: Callable[[], tuple[SegmentBackend, int] | None]) -> None:
        """Attach the backend that ``callback()`` returns once the graph holds ``threshold`` nodes."""

    def clear_paging_policy(self) -> None: ...
    @property
    def paged(self) -> bool: ...
    @property
    def budget_bytes(self) -> int | None: ...
    @budget_bytes.setter
    def budget_bytes(self, value: int) -> None: ...
    def flush(self) -> None:
        """Write every dirty resident segment back (segments stay resident)."""

    def evict_all(self) -> None: ...
    def compact(self) -> None:
        """Drop allocation slack in every resident segment (ids unchanged)."""

    def stats(self) -> dict[str, Any]:
        """loads, evictions, writebacks, segments, resident_segments, resident_bytes, paged, budget_bytes."""

    # nodes
    def number_of_nodes(self) -> int: ...
    def number_of_edges(self) -> int: ...
    def add_node(self, addr: int, size: int) -> tuple[int, bool]:
        """networkx add_node. Returns (id, created)."""

    def find_node(self, addr: int, size: int) -> int | None: ...
    def contains_node(self, idx: int) -> bool: ...
    def node_key(self, idx: int) -> tuple[int, int]: ...
    def node_addr(self, idx: int) -> int: ...
    def nodes(self) -> list[int]:
        """Live node ids in insertion order."""

    def node_keys(self) -> list[tuple[int, int]]: ...
    def remove_node(self, idx: int) -> bool: ...
    def nodes_at_addr(self, addr: int) -> list[int]: ...
    def first_node_at_addr(self, addr: int) -> int | None: ...
    def has_addr(self, addr: int) -> bool: ...
    def addrs(self) -> list[int]: ...

    # edges
    def add_edge(
        self,
        src: int,
        dst: int,
        present: int = 0,
        jumpkind: str | None = None,
        ins_addr: int | None = None,
        stmt_idx: int | None = None,
    ) -> bool:
        """networkx add_edge; attributes whose PRESENT_* bit is set overwrite, the others are kept. Returns True
        if the edge is new."""

    def remove_edge(self, src: int, dst: int) -> bool: ...
    def has_edge(self, src: int, dst: int) -> bool: ...
    def edge_data(self, src: int, dst: int) -> dict | None: ...
    def edge_tuple(self, src: int, dst: int) -> tuple[str | None, int | None, int | None] | None: ...
    def edge_jumpkind(self, src: int, dst: int) -> str | None: ...
    def edges(self) -> list[tuple[int, int]]: ...
    def edges_with_data(self) -> list[tuple[int, int, dict]]: ...
    def edges_with_tuples(self) -> list[tuple[int, int, str | None, int | None, int | None]]: ...
    def out_edges(self, idx: int) -> list[tuple[int, int]]: ...
    def in_edges(self, idx: int) -> list[tuple[int, int]]: ...
    def out_edges_with_data(self, idx: int) -> list[tuple[int, int, dict]]: ...
    def in_edges_with_data(self, idx: int) -> list[tuple[int, int, dict]]: ...
    def out_edges_jumpkinds(self, idx: int) -> list[tuple[int, str | None]]: ...
    def in_edges_jumpkinds(self, idx: int) -> list[tuple[int, str | None]]: ...
    def successors(self, idx: int) -> list[int]: ...
    def predecessors(self, idx: int) -> list[int]: ...
    def out_degree(self, idx: int) -> int: ...
    def in_degree(self, idx: int) -> int: ...
    def is_call_destination(self, idx: int) -> bool: ...
    def call_destinations(self) -> list[int]: ...

    # serialization
    def to_bytes(self) -> bytes: ...
    @classmethod
    def from_bytes(cls, data: bytes) -> CfgGraph: ...
    def to_blobs(self) -> tuple[bytes, list[bytes]]:
        """(header, [segment blob, ...]); evicted segments are copied out of the backend without decoding."""

    @classmethod
    def from_blobs(cls, header: bytes, blobs: list[bytes]) -> CfgGraph: ...
