from collections.abc import Callable
from typing import Any

PRESENT_TYPE: int
PRESENT_OUTSIDE: int
PRESENT_INS_ADDR: int
PRESENT_STMT_IDX: int
PRESENT_CONFIRMED: int

class NodeKind:
    """Kind of a node in a function transition graph; mirrors the CodeNode subclasses."""

    BLOCK: NodeKind
    FUNC: NodeKind
    HOOK: NodeKind
    SYSCALL: NodeKind
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class EdgeKind:
    """The ``type`` attribute of a transition-graph edge."""

    TRANSITION: EdgeKind
    CALL: EdgeKind
    FAKE_RETURN: EdgeKind
    RETURN: EdgeKind
    EXCEPTION: EdgeKind
    SYSCALL: EdgeKind
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class SiteKind:
    """Function.ret_sites / jumpout_sites / callout_sites / retout_sites membership."""

    RET: SiteKind
    JUMPOUT: SiteKind
    CALLOUT: SiteKind
    RETOUT: SiteKind
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class EndpointKind:
    """The sort of a function endpoint (the keys of Function.endpoints_with_type)."""

    CALL: EndpointKind
    RETURN: EndpointKind
    TRANSITION: EndpointKind
    EXCEPTION: EndpointKind
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class FunctionGraph:
    """
    Packed storage for the transition graph of a Function: a node table, an edge table with the networkx edge
    attributes, the local-block/block-size/block-node maps, endpoint and site flags, call sites and the startpoint.

    Node ids are indices into the node table and stay valid for the lifetime of the graph; ``remove_node`` only
    removes a node from the graph (and its edges), the maps that refer to it are untouched.

    ``to_bytes()`` writes blob format version 2 (nodes carry ``delta``; user-supplied node bytes are stored in a
    side table); ``from_bytes()`` accepts only that version and raises ValueError for any other version byte.
    """

    func_addr: int
    startpoint: int | None

    def __init__(self, func_addr: int) -> None: ...
    def copy(self) -> FunctionGraph: ...
    # nodes
    def number_of_nodes(self) -> int: ...
    def number_of_edges(self) -> int: ...
    def add_node(self, kind: NodeKind, addr: int, size: int, thumb: bool, delta: int = 0) -> tuple[int, bool]:
        """networkx add_node. Returns (id, created); delta is recorded for a new record only."""

    def register_node(
        self, is_local: bool, kind: NodeKind, addr: int, size: int, thumb: bool, delta: int = 0
    ) -> tuple[int, bool, bool, bool]:
        """Port of Function.register_node. Returns (id, created, new_local, changed)."""

    def node_delta(self, idx: int) -> int:
        """delta of a node id: its bytes live at addr + delta."""

    def node_bytes(self, idx: int) -> bytes | None:
        """The user-supplied bytes of a node, or None if its bytes come from the loader."""

    def set_node_bytes(self, idx: int, data: bytes) -> None:
        """Store user-supplied bytes for a node."""

    def find_node(self, kind: NodeKind, addr: int, size: int, thumb: bool) -> int | None: ...
    def contains_node(self, idx: int) -> bool: ...
    def node(self, idx: int) -> tuple[NodeKind, int, int, bool]:
        """(kind, addr, size, thumb) of a node id."""

    def node_addr(self, idx: int) -> int: ...
    def node_size(self, idx: int) -> int: ...
    def node_kind(self, idx: int) -> NodeKind: ...
    def nodes(self) -> list[int]: ...
    def remove_node(self, idx: int) -> bool: ...
    # edges
    def add_edge(
        self,
        src: int,
        dst: int,
        kind: EdgeKind,
        present: int,
        outside: bool = False,
        ins_addr: int | None = None,
        stmt_idx: int | None = None,
        confirmed: bool = False,
    ) -> bool:
        """networkx add_edge(u, v, **data); ``present`` is a PRESENT_* mask of the given keys. Returns True if new."""

    def remove_edge(self, src: int, dst: int) -> bool: ...
    def has_edge(self, src: int, dst: int) -> bool: ...
    def edge_data(self, src: int, dst: int) -> dict[str, Any] | None: ...
    def set_edge_confirmed(self, src: int, dst: int, confirmed: bool) -> None: ...
    def edge_kind(self, src: int, dst: int) -> EdgeKind | None: ...
    def edge_is_outside(self, src: int, dst: int) -> bool | None: ...
    def edge_confirmed(self, src: int, dst: int) -> bool | None: ...
    def edges(self) -> list[tuple[int, int]]: ...
    def edges_with_data(self) -> list[tuple[int, int, dict[str, Any]]]: ...
    def local_edges_with_data(self) -> list[tuple[int, int, dict[str, Any]]]: ...
    def edges_of_kind(self, kind: EdgeKind) -> list[tuple[int, int]]: ...
    def out_edges(self, idx: int) -> list[tuple[int, int]]: ...
    def in_edges(self, idx: int) -> list[tuple[int, int]]: ...
    def successors(self, idx: int) -> list[int]: ...
    def predecessors(self, idx: int) -> list[int]: ...
    def out_degree(self, idx: int) -> int: ...
    def in_degree(self, idx: int) -> int: ...
    def outgoing_function_targets(self) -> list[tuple[int, bool]]:
        """(addr, is_call) of callees and outside-transition targets."""

    # local blocks, block sizes
    def local_at(self, addr: int) -> int | None: ...
    def set_local_at(self, addr: int, idx: int) -> None: ...
    def is_local(self, addr: int) -> bool: ...
    def local_addrs(self) -> list[int]: ...
    def local_items(self) -> list[tuple[int, int]]: ...
    def local_count(self) -> int: ...
    def local_size(self) -> int: ...
    def block_node_at(self, addr: int) -> int | None: ...
    def set_block_node_at(self, addr: int, idx: int) -> None: ...
    def block_size(self, addr: int) -> int | None: ...
    def set_block_size(self, addr: int, size: int) -> None: ...
    def has_block_size(self, addr: int) -> bool: ...
    # sites and endpoints
    def add_site(self, idx: int, kind: SiteKind) -> None: ...
    def has_site(self, idx: int, kind: SiteKind) -> bool: ...
    def sites(self, kind: SiteKind) -> list[int]: ...
    def add_endpoint(self, idx: int, kind: EndpointKind) -> None: ...
    def has_endpoint(self, idx: int, kind: EndpointKind) -> bool: ...
    def endpoints(self, kind: EndpointKind) -> list[int]: ...
    def has_any_endpoint(self) -> bool: ...
    # call sites
    def add_call_site(self, addr: int, target: int | None, ret: int | None) -> None: ...
    def call_site(self, addr: int) -> tuple[int | None, int | None] | None: ...
    def call_sites(self) -> list[tuple[int, int | None, int | None]]: ...
    def call_site_addrs(self) -> list[int]: ...
    # normalization
    def normalize(self, is_arm: bool, branch_ins_addr: Callable[[int, int], int | None]) -> None:
        """Split overlapping blocks that share an end address (Function.normalize)."""

    # serialization
    def to_bytes(self) -> bytes: ...
    @classmethod
    def from_bytes(cls, data: bytes) -> FunctionGraph: ...
    @staticmethod
    def local_block_addrs_from_bytes(data: bytes) -> list[int]: ...

__all__ = [
    "PRESENT_CONFIRMED",
    "PRESENT_INS_ADDR",
    "PRESENT_OUTSIDE",
    "PRESENT_STMT_IDX",
    "PRESENT_TYPE",
    "EdgeKind",
    "EndpointKind",
    "FunctionGraph",
    "NodeKind",
    "SiteKind",
]
