"""Type stubs for ``angr.rustylib.claripy.errors``."""

class ClaripyError(Exception): ...
class ClaripyTypeError(ClaripyError): ...
class UnsatError(ClaripyError): ...
class ClaripyFrontendError(ClaripyError): ...
class ClaripySolverInterruptError(ClaripyError): ...
class ClaripyOperationError(ClaripyError): ...
class ClaripyZeroDivisionError(ClaripyOperationError): ...
class InvalidExtractBounds(ClaripyOperationError): ...

__all__ = [
    "ClaripyError",
    "ClaripyFrontendError",
    "ClaripyOperationError",
    "ClaripySolverInterruptError",
    "ClaripyTypeError",
    "ClaripyZeroDivisionError",
    "InvalidExtractBounds",
    "UnsatError",
]
