"""Type stubs for ``angr.rustylib.claripy.vsa``."""

from angr.rustylib.claripy.ast.base import Base
from angr.rustylib.claripy.ast.bool import Bool
from angr.rustylib.claripy.ast.bv import BV

def reduce(expr: Base) -> Base: ...
def simplify(expr: Base) -> Base: ...
def is_true(expr: Bool) -> bool: ...
def is_false(expr: Bool) -> bool: ...
def has_true(expr: Bool) -> bool: ...
def has_false(expr: Bool) -> bool: ...
def min(expr: BV, signed: bool = False) -> int: ...
def max(expr: BV, signed: bool = False) -> int: ...
def eval(expr: BV, n: int) -> list[int]: ...
def cardinality(expr: BV) -> int: ...
def identical(a: Base, b: Base) -> bool: ...

__all__ = [
    "cardinality",
    "eval",
    "has_false",
    "has_true",
    "identical",
    "is_false",
    "is_true",
    "max",
    "min",
    "reduce",
    "simplify",
]
