from __future__ import annotations

from angr.analyses.decompiler.optimization_passes import (
    BasePointerSaveSimplifier,
    CallStatementRewriter,
    ConditionConstantPropagation,
    ConstantDereferencesSimplifier,
    DeadblockRemover,
    DetermineLoadSizes,
    EagerStdStringConcatenationPass,
    ExprOpSwapper,
    FlipBooleanCmp,
    InlinedMemcpySimplifier,
    InlinedMemcpySimplifierLate,
    InlinedMemsetSimplifier,
    InlinedMemsetSimplifierLate,
    InlinedStrcpySimplifier,
    InlinedStrcpySimplifierLate,
    InlinedStringTransformationSimplifier,
    InlinedStrlenSimplifier,
    InlinedWcscpySimplifier,
    InlinedWcscpySimplifierLate,
    ITEExprConverter,
    ITERegionConverter,
    KnownPatternOutliner,
    LoweredSwitchSimplifier,
    MipsGpSettingSimplifier,
    PostStructuringPeepholeOptimizationPass,
    RegisterSaveAreaSimplifier,
    RegisterSaveAreaSimplifierAdvanced,
    RetAddrSaveSimplifier,
    ReturnDeduplicator,
    ReturnDuplicatorHigh,
    ReturnDuplicatorLow,
    StackCanarySimplifier,
    SwitchDefaultCaseDuplicator,
    SwitchReusedEntryRewriter,
    WinStackCanarySimplifier,
    X86GccGetPcSimplifier,
)

from .preset import DecompilationPreset

preset_fast = DecompilationPreset(
    "fast",
    [
        RegisterSaveAreaSimplifier,
        StackCanarySimplifier,
        WinStackCanarySimplifier,
        RegisterSaveAreaSimplifierAdvanced,
        BasePointerSaveSimplifier,
        ConstantDereferencesSimplifier,
        RetAddrSaveSimplifier,
        X86GccGetPcSimplifier,
        MipsGpSettingSimplifier,
        ITERegionConverter,
        ITEExprConverter,
        ExprOpSwapper,
        ReturnDuplicatorHigh,
        DeadblockRemover,
        SwitchDefaultCaseDuplicator,
        SwitchReusedEntryRewriter,
        LoweredSwitchSimplifier,
        ReturnDuplicatorLow,
        ReturnDeduplicator,
        FlipBooleanCmp,
        # Simplify string transformation loops before other inlined string/memory operations use simplified output
        InlinedStringTransformationSimplifier,
        InlinedMemcpySimplifier,
        InlinedMemsetSimplifier,
        InlinedStrcpySimplifier,
        InlinedWcscpySimplifier,
        InlinedMemcpySimplifierLate,
        InlinedMemsetSimplifierLate,
        InlinedStrcpySimplifierLate,
        InlinedWcscpySimplifierLate,
        InlinedStrlenSimplifier,
        KnownPatternOutliner,
        CallStatementRewriter,
        ConditionConstantPropagation,
        DetermineLoadSizes,
        PostStructuringPeepholeOptimizationPass,
        EagerStdStringConcatenationPass,
    ],
)


__all__ = ["preset_fast"]
