name: $(BuildDefinitionName)-$(SourceBranchName)-$(BuildID)

resources:
  repositories:
  - repository: ci-settings
    type: github
    name: angr/ci-settings
    endpoint: angr

stages:
- template: resources/master.yml@ci-settings
