name: $(BuildDefinitionName)-$(Date:yyyyMMdd)-$(BuildID)
trigger: none
pr: none
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

resources:
  repositories:
  - repository: ci-settings
    type: github
    name: angr/ci-settings
    endpoint: angr

stages:
- template: resources/nightly.yml@ci-settings
