#!/bin/sh
# Reset the System Clock to UTC if the hardware clock from which it
# was copied by the kernel was in localtime.

dev=$1

if [ -f /etc/default/rcS ] ; then
    . /etc/default/rcS
fi	

if [ yes != "$UTC" ] ; then
    if [ yes = "$BADYEAR" ] ; then
	/sbin/hwclock --rtc=$dev --systz --localtime --noadjfile --badyear
    else
	/sbin/hwclock --rtc=$dev --systz --localtime --noadjfile
    fi
fi
