name: "CI"
on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Formatting & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          rustflags: ""

      - name: Rustfmt Check
        id: rustfmt
        uses: actions-rust-lang/rustfmt@v1
        continue-on-error: true

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@v6

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad

      - name: Clippy Check
        id: clippy
        run: cargo clippy --all-features -- -D warnings
        continue-on-error: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
          CMAKE_C_COMPILER_LAUNCHER: "sccache"
          CMAKE_CXX_COMPILER_LAUNCHER: "sccache"
          CMAKE_MSVC_DEBUG_INFORMATION_FORMAT: Embedded
          CMAKE_POLICY_CMP0141: NEW
          CMAKE_GENERATOR: Ninja
          CC: "clang"
          CXX: "clang++"

      - name: Check results
        if: steps.rustfmt.outcome == 'failure' || steps.clippy.outcome == 'failure'
        run: exit 1

  test:
    name: Rust Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@v6

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad

      - name: Build
        run: cargo build --all-features
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
          CMAKE_C_COMPILER_LAUNCHER: "sccache"
          CMAKE_CXX_COMPILER_LAUNCHER: "sccache"
          CMAKE_MSVC_DEBUG_INFORMATION_FORMAT: Embedded
          CMAKE_POLICY_CMP0141: NEW
          CMAKE_GENERATOR: Ninja
          CC: "clang"
          CXX: "clang++"

      - name: Run tests
        run: cargo test --all-features --no-fail-fast

  build-wheels:
    name: Python Wheel (${{ matrix.os }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"]
        include:
          - os: ubuntu-latest
            python-version: "3.14"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@v6

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad

      - name: Install Maturin
        run: pip install maturin

      - name: Build Wheel
        run: maturin build --release -o dist
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
          CMAKE_C_COMPILER_LAUNCHER: "sccache"
          CMAKE_CXX_COMPILER_LAUNCHER: "sccache"
          CMAKE_MSVC_DEBUG_INFORMATION_FORMAT: Embedded
          CMAKE_POLICY_CMP0141: NEW
          CMAKE_GENERATOR: Ninja
          CC: "clang"
          CXX: "clang++"

      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*.whl
