name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  ci:
    uses: angr/ci-settings/.github/workflows/angr-ci.yml@master

  installation:
    name: Test installation (${{ matrix.environment.os }}, py${{ matrix.environment.python-version }})
    strategy:
      matrix:
        environment:
          - os: windows-2025
            python-version: 3.12
          - os: macos-26
            python-version: 3.12
          - os: ubuntu-24.04
            python-version: 3.14
      fail-fast: false
    runs-on: ${{ matrix.environment.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1
        if: startsWith(runner.os, 'windows')
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v6
      - name: Sync dependencies
        run: uv sync -p ${{ matrix.environment.python-version }}
      - name: Collect tests
        run: uv run pytest --collect-only tests

  rust_check:
    name: Rust Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1
        with:
          components: clippy, rustfmt
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo fmt --all -- --check

  rust_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v5
        with:
          python-version: "3.12"
      - run: cargo test --release
