name: Nightly Corpus Test

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/corpus_test.yml
    with:
      corpus_github_path: "stable"
      nightly: true
