name: Nightly CI

on:
  schedule:
  - cron: "0 0 * * *"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/nightly-ci.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout angr
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          path: angr
      - name: Checkout binaries
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          repository: angr/binaries
          path: binaries
      - name: Setup MSVC for Windows
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1
      - name: Setup Java for pysoot
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v6
        with:
          python-version: 3.12
          working-directory: angr
      - name: Run pytest
        run: uv run pytest -n auto
        working-directory: angr
