name: Performance Benchmarking CI

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
  pull_request:

jobs:
  perf:
    name: Perfharness
    runs-on: ubuntu-22.04
    container:
      image: angr/ci:3
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: angr/angr-dev
    - name: Install
      run: |
          python3 -mvirtualenv venv && . venv/bin/activate
          pip install pytest-codspeed
          git clone https://github.com/angr/angr.git
          git -C angr fetch origin ${{ github.ref }} && git -C angr switch --detach FETCH_HEAD
          ./extremely-simple-setup.sh
    - name: Test
      uses: CodSpeedHQ/action@v3
      with:
        run: |
          . venv/bin/activate
          cd angr
          pytest $(find tests -name 'perf_*.py') --codspeed
        token: ${{ secrets.CODSPEED_TOKEN }}
