name: Performance Benchmarking CI

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
  pull_request:

jobs:
  perf:
    name: Perfharness
    runs-on: codspeed-macro
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        path: angr
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        repository: angr/binaries
        path: binaries
    - uses: astral-sh/setup-uv@445689ea25e0de0a23313031f5fe577c74ae45a1 # v6
    - name: Install
      run: uv --directory angr sync -p 3.12
    - name: Test
      uses: CodSpeedHQ/action@v3
      with:
        run: |
          uv --directory angr run pytest --codspeed $(find tests -name 'perf_*.py')
        token: ${{ secrets.CODSPEED_TOKEN }}
