name: Test on Windows and macOS

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  windows:
    name: Test Windows
    runs-on: windows-2022
    strategy:
      matrix:
        group: [1, 2, 3, 4, 5]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          path: angr
      - uses: actions/checkout@v3
        with:
          repository: angr/binaries
          path: binaries
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: python -m venv $HOME\venv
        name: Create venv
      - run: |
          call %USERPROFILE%\venv\Scripts\activate
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          pip install "setuptools>=59" wheel cffi "unicorn==2.0.1"
          pip install git+https://github.com/angr/archinfo.git
          pip install git+https://github.com/angr/pyvex.git
          pip install git+https://github.com/angr/cle.git
          pip install git+https://github.com/angr/claripy.git
          pip install git+https://github.com/angr/ailment.git
        name: Install dependencies
        shell: cmd
      - run: |
          call %USERPROFILE%\venv\Scripts\activate
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          pip install --no-build-isolation .\angr[testing]
        name: Install angr
        shell: cmd
      - run: |
          call %USERPROFILE%\venv\Scripts\activate
          pytest --splits 5 --group ${{ matrix.group }} -n auto angr
        name: Run pytest
        shell: cmd
        env:
          SKIP_SLOW_TESTS: true

  macos:
    name: Test macOS
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          path: angr
      - uses: actions/checkout@v3
        with:
          repository: angr/binaries
          path: binaries
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: python -m venv $HOME/venv
        name: Create venv
        shell: bash
      - run: |
          source $HOME/venv/bin/activate
          pip install "setuptools>=59" wheel cffi "unicorn==2.0.1"
          pip install git+https://github.com/angr/archinfo.git
          pip install git+https://github.com/angr/pyvex.git
          pip install git+https://github.com/angr/cle.git
          pip install git+https://github.com/angr/claripy.git
          pip install git+https://github.com/angr/ailment.git
        name: Install dependencies
      - run: |
          source $HOME/venv/bin/activate
          pip install --no-build-isolation ./angr[testing]
        name: Install angr
      - run: |
          source $HOME/venv/bin/activate
          pytest -n auto angr
        name: Run pytest
        env:
          SKIP_SLOW_TESTS: true
