name: Run pre-commit checks

on:
  push:
  pull_request:

jobs:
  check:
    name: Test Windows installation
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: pip install pre-commit
      - run: pre-commit run --source HEAD^ --all-files
