name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          days-before-stale: 120
          stale-issue-message: >
            This issue has been marked as `stale` because it has no recent activity.
            Please comment or add the `pinned` tag to prevent this issue from being closed.
          stale-pr-message: >
            This pull request has been marked as `stale` because it has no recent activity.
            Please comment or add the `pinned` tag to prevent this issue from being closed.
          close-issue-message: >
            This issue has been closed due to inactivity.
          close-pr-message: >
            This issue has been closed due to inactivity.
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: 'pinned,feature,enhancement,help wanted'
          exempt-pr-labels: 'pinned'
          exempt-all-issue-assignees: true
          operations-per-run: 60
