name: Windows Smoketest

on:
  push:
    paths:
      - "native"
      - ".github/workflows/windows-smoketest.yml"
  pull_request:
    paths:
      - "native"
      - ".github/workflows/windows-smoketest.yml"
  workflow_dispatch:

jobs:
  test:
    name: Test Windows installation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          pip install git+https://github.com/angr/archinfo.git
          pip install git+https://github.com/angr/pyvex.git
          pip install git+https://github.com/angr/cle.git
          pip install git+https://github.com/angr/claripy.git
          pip install git+https://github.com/angr/ailment.git
        name: Install dependencies
        shell: cmd
      - run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          pip install --no-build-isolation .
        name: Install angr
        shell: cmd
      - runs: python -c "import angr; print('It works!')"
        name: Import angr
