name: Test on Windows

on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  windows:
    name: Test Windows
    runs-on: windows-2022
    strategy:
      matrix:
        runnner_id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          path: angr
      - uses: actions/checkout@v3
        with:
          repository: angr/binaries
          path: binaries
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: python -m venv $HOME/venv
        name: Create venv
        shell: bash
      - run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call %USERPROFILE%\venv\Scripts\activate
          pip install "setuptools>=59" wheel cffi "unicorn==2.0.1.post1"
          pip install git+https://github.com/angr/archinfo.git
          pip install git+https://github.com/angr/pyvex.git
          pip install git+https://github.com/angr/cle.git
          pip install git+https://github.com/angr/claripy.git
          pip install git+https://github.com/angr/ailment.git
        name: Install dependencies
        shell: cmd
      - run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call %USERPROFILE%\venv\Scripts\activate
          pip install --no-build-isolation ./angr[testing]
        name: Install angr
        shell: cmd
      - run: |
          call %USERPROFILE%\venv\Scripts\activate
          pytest -n auto --splits 10 --group ${{ matrix.runner_id }} angr
        name: Run pytest
        env:
          SKIP_SLOW_TESTS: true
        shell: cmd
